import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';

class PDFReportService {
  static Future<void> generateWeeklyReport({
    required List<String> todos,
    required List<String> habits,
    required double totalExpenses,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(level: 0, child: pw.Text('Weekly Productivity Report')),
              pw.SizedBox(height: 20),
              pw.Text('Date: ${DateTime.now().toString().split(' ')[0]}'),
              pw.Divider(),
              pw.Header(level: 1, child: pw.Text('Tasks Completed')),
              ...todos.map((t) => pw.Bullet(text: t)),
              pw.SizedBox(height: 10),
              pw.Header(level: 1, child: pw.Text('Habits Maintained')),
              ...habits.map((h) => pw.Bullet(text: h)),
              pw.SizedBox(height: 10),
              pw.Header(level: 1, child: pw.Text('Financial Summary')),
              pw.Text('Total Weekly Expenses: \$${totalExpenses.toStringAsFixed(2)}'),
              pw.SizedBox(height: 30),
              pw.Footer(
                title: pw.Text('Generated by OmniPro Productivity - 100% Offline & Private'),
              ),
            ],
          );
        },
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File("${output.path}/weekly_report.pdf");
    await file.writeAsBytes(await pdf.save());
    await Printing.sharePdf(bytes: await pdf.save(), filename: 'weekly_report.pdf');
  }
}
